/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getaxi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldinho Augusto
 */
public class cadastroAtendenteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form telaCliente
     */
    private int idAtendente;
    
    public cadastroAtendenteJFrame() {
        initComponents();
        consultarID();
    }

    public void consultarID()
    {
        ResultSet rs;
        
        // TODO add your handling code here:
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");            
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("SELECT idatendente from atendente");
            rs = instrucao.executeQuery();                                                         
            
            while(rs.next())
            {
                idAtendente = rs.getInt(1);
            }
            idAtendente += 1;
            
            txtIDAtendente.setText(""+idAtendente);
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        iconPerfil = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblIDAtendente = new javax.swing.JLabel();
        lblRuaAtendente = new javax.swing.JLabel();
        lblCidadeAtendente = new javax.swing.JLabel();
        lblEstadoAtendente = new javax.swing.JLabel();
        lblTelefoneAtendente = new javax.swing.JLabel();
        txtCPF = new JtextFieldSomenteNumeros(14);
        txtNOME = new JtextFieldSomenteLetras(50);
        txtIDAtendente = new javax.swing.JTextField();
        txtRuaAtendente = new JtextFieldSomenteLetras(30);
        txtCidadeAtendente = new JtextFieldSomenteLetras(15);
        txtEstadoAtendente = new JtextFieldSomenteLetras(2);
        txtTelefoneAtendente = new JtextFieldSomenteNumeros(14);
        btnCadastrarAtendente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Motorista");
        setResizable(false);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CADASTRAR ATENDENTE");

        lblCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCpf.setText("CPF:");

        iconPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/iconPerfil.png"))); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome.setText("NOME:");

        lblIDAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIDAtendente.setText("ID");

        lblRuaAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRuaAtendente.setText("RUA:");

        lblCidadeAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCidadeAtendente.setText("CIDADE:");

        lblEstadoAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstadoAtendente.setText("ESTADO:");

        lblTelefoneAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefoneAtendente.setText("TELEFONE:");

        txtCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFKeyReleased(evt);
            }
        });

        txtNOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMEActionPerformed(evt);
            }
        });

        txtIDAtendente.setEditable(false);
        txtIDAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtRuaAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaAtendenteActionPerformed(evt);
            }
        });

        txtTelefoneAtendente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneAtendenteKeyReleased(evt);
            }
        });

        btnCadastrarAtendente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCadastrarAtendente.setText("CADASTRAR");
        btnCadastrarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtendenteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ENDEREÇO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iconPerfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIDAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRuaAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCidadeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEstadoAtendente)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEstadoAtendente))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCadastrarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelefoneAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuaAtendente)
                            .addComponent(lblCidadeAtendente)
                            .addComponent(lblTelefoneAtendente)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIDAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIDAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuaAtendente)
                    .addComponent(txtRuaAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeAtendente)
                    .addComponent(txtCidadeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoAtendente)
                    .addComponent(txtEstadoAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneAtendente)
                    .addComponent(txtTelefoneAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnCadastrarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtendenteActionPerformed
        // TODO add your handling code here:
        try
        {
            boolean isOk = false;
            
            if(txtNOME.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Favor digitar um nome valido (ate 50 caracteres, sem numeros)");
                isOk = false;                
            }
            if(txtCPF.getText().isEmpty() || txtCPF.getText().length() != 14)
            {
                JOptionPane.showMessageDialog(null,"Favor digitar um documento de CPF valido, com 11 DIGITOS");
                isOk = false;
            }
            
            else
            {
                isOk = true;
            }                       

            if(isOk)
            {
                //realizar o carregamento do JDBC
                Class.forName("org.postgresql.Driver");
                //construindo a conexao com o SGDB PostgreSQL
                Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");            
                //construcao da classe PreparedStatement para passagem de parametros
                PreparedStatement instrucao = conexao.prepareStatement("INSERT INTO atendente VALUES(?,?,?,?,?,?,?)");
                
                instrucao.setInt(1, idAtendente);            
                instrucao.setString(2, txtNOME.getText().toUpperCase());
                instrucao.setString(3, txtCPF.getText());            
                instrucao.setString(4, txtEstadoAtendente.getText().toUpperCase());
                instrucao.setString(5, txtCidadeAtendente.getText().toUpperCase());
                instrucao.setString(6, txtRuaAtendente.getText().toUpperCase());
                instrucao.setString(7, txtTelefoneAtendente.getText());                        

                //executando a SQL parametrizada
                instrucao.executeUpdate();    
            
                JOptionPane.showMessageDialog(null,"REGISTRO GRAVADO!");
                idAtendente++;
                txtNOME.setText("");
                txtCPF.setText("");                                                              
                txtEstadoAtendente.setText("");
                txtCidadeAtendente.setText("");
                txtRuaAtendente.setText("");
                txtTelefoneAtendente.setText("");
                txtIDAtendente.setText(""+idAtendente); 
            }        
            
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarAtendenteActionPerformed

    private void txtNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMEActionPerformed

    private void txtRuaAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaAtendenteActionPerformed

    private void txtCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyReleased
        // TODO add your handling code here:
        try
        {
            if(txtCPF.getText().length()<13)
            {
            txtCPF.setText(""+txtCPF.getText().charAt(0)+txtCPF.getText().charAt(1)+
                                            txtCPF.getText().charAt(2)+"."+txtCPF.getText().charAt(3)+
                                            txtCPF.getText().charAt(4)+txtCPF.getText().charAt(5)+"."+
                                            txtCPF.getText().charAt(6)+txtCPF.getText().charAt(7)+txtCPF.getText().charAt(8)+"-"+
                                            txtCPF.getText().charAt(9)+txtCPF.getText().charAt(10));
            }           
        }
        catch(StringIndexOutOfBoundsException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtCPFKeyReleased

    private void txtTelefoneAtendenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneAtendenteKeyReleased
        // TODO add your handling code here:
        try
        {
            if(txtTelefoneAtendente.getText().length()<13)
            {
            txtTelefoneAtendente.setText("("+txtTelefoneAtendente.getText().charAt(0)+txtTelefoneAtendente.getText().charAt(1)+")"+
                                            txtTelefoneAtendente.getText().charAt(2)+txtTelefoneAtendente.getText().charAt(3)+
                                            txtTelefoneAtendente.getText().charAt(4)+txtTelefoneAtendente.getText().charAt(5)+
                                            txtTelefoneAtendente.getText().charAt(6)+"-"+txtTelefoneAtendente.getText().charAt(7)+txtTelefoneAtendente.getText().charAt(8)+
                                            txtTelefoneAtendente.getText().charAt(9)+txtTelefoneAtendente.getText().charAt(10));
            }           
        }
        catch(StringIndexOutOfBoundsException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtTelefoneAtendenteKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroAtendenteJFrame().setVisible(true);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAtendente;
    private javax.swing.JLabel iconPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCidadeAtendente;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEstadoAtendente;
    private javax.swing.JLabel lblIDAtendente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRuaAtendente;
    private javax.swing.JLabel lblTelefoneAtendente;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidadeAtendente;
    private javax.swing.JTextField txtEstadoAtendente;
    private javax.swing.JTextField txtIDAtendente;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtRuaAtendente;
    private javax.swing.JTextField txtTelefoneAtendente;
    // End of variables declaration//GEN-END:variables
}
