/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getaxi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldinho Augusto
 */
public class cadastroAtendenteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form telaCliente
     */
    private int idAtendente;
    
    public cadastroAtendenteJFrame() {
        initComponents();
        if(idAtendente == 0)
        {
            idAtendente = 1;
        }
        txtIDAtendente.setText(""+idAtendente);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        iconPerfil = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblIDAtendente = new javax.swing.JLabel();
        lblSalarioAtendente = new javax.swing.JLabel();
        lblRuaAtendente = new javax.swing.JLabel();
        lblCidadeAtendente = new javax.swing.JLabel();
        lblEstadoAtendente = new javax.swing.JLabel();
        lblTelefoneAtendente = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtNOME = new javax.swing.JTextField();
        txtIDAtendente = new javax.swing.JTextField();
        txtSalarioAtendente = new javax.swing.JTextField();
        txtRuaAtendente = new javax.swing.JTextField();
        txtCidadeAtendente = new javax.swing.JTextField();
        txtEstadoAtendente = new javax.swing.JTextField();
        txtTelefoneAtendente = new javax.swing.JTextField();
        btnCadastrarAtendente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Motorista");
        setResizable(false);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CADASTRAR ATENDENTE");

        lblCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCpf.setText("CPF:");

        iconPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/iconPerfil.png"))); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome.setText("NOME:");

        lblIDAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIDAtendente.setText("ID");

        lblSalarioAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSalarioAtendente.setText("SALARIO:");

        lblRuaAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRuaAtendente.setText("RUA:");

        lblCidadeAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCidadeAtendente.setText("CIDADE:");

        lblEstadoAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstadoAtendente.setText("ESTADO:");

        lblTelefoneAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefoneAtendente.setText("TELEFONE:");

        txtCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        txtNOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMEActionPerformed(evt);
            }
        });

        txtIDAtendente.setEditable(false);
        txtIDAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtRuaAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaAtendenteActionPerformed(evt);
            }
        });

        btnCadastrarAtendente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCadastrarAtendente.setText("CADASTRAR");
        btnCadastrarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtendenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCadastrarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iconPerfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIDAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSalarioAtendente)
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRuaAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalarioAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCidadeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEstadoAtendente)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEstadoAtendente))
                                    .addComponent(txtTelefoneAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuaAtendente)
                            .addComponent(lblCidadeAtendente)
                            .addComponent(lblTelefoneAtendente))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIDAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIDAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioAtendente)
                    .addComponent(txtSalarioAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuaAtendente)
                    .addComponent(txtRuaAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeAtendente)
                    .addComponent(txtCidadeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoAtendente)
                    .addComponent(txtEstadoAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneAtendente)
                    .addComponent(txtTelefoneAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btnCadastrarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnCadastrarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtendenteActionPerformed
        // TODO add your handling code here:
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");
            JOptionPane.showMessageDialog(null,"CONEXAO REALIZADA!");
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("INSERT INTO atendente VALUES(?,?,?,?,?,?,?,?)");
            
            instrucao.setInt(1, idAtendente);            
            instrucao.setString(2, txtNOME.getText());
            instrucao.setInt(3, 0);
            instrucao.setString(4, txtCPF.getText());            
            instrucao.setString(5, txtEstadoAtendente.getText());
            instrucao.setString(6, txtCidadeAtendente.getText());
            instrucao.setString(7, txtRuaAtendente.getText());
            instrucao.setString(8, txtTelefoneAtendente.getText());                        
            
            //executando a SQL parametrizada
            instrucao.executeUpdate();            
            
            if(txtNOME.getText() == "")
            {
                JOptionPane.showMessageDialog(null,"Favor digitar um nome valido");
            }
            if(txtCPF.getText() == "")
            {
                JOptionPane.showMessageDialog(null,"Favor digitar um documento de CPF valido");
            }            
            
            JOptionPane.showMessageDialog(null,"REGISTRO GRAVADO!");
            
            idAtendente++;
            txtNOME.setText("");
            txtCPF.setText("");                                  
            txtSalarioAtendente.setText("");            
            txtEstadoAtendente.setText("");
            txtCidadeAtendente.setText("");
            txtRuaAtendente.setText("");
            txtTelefoneAtendente.setText("");                                    
            
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarAtendenteActionPerformed

    private void txtNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMEActionPerformed

    private void txtRuaAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaAtendenteActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroAtendenteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroAtendenteJFrame().setVisible(true);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAtendente;
    private javax.swing.JLabel iconPerfil;
    private javax.swing.JLabel lblCidadeAtendente;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEstadoAtendente;
    private javax.swing.JLabel lblIDAtendente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRuaAtendente;
    private javax.swing.JLabel lblSalarioAtendente;
    private javax.swing.JLabel lblTelefoneAtendente;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidadeAtendente;
    private javax.swing.JTextField txtEstadoAtendente;
    private javax.swing.JTextField txtIDAtendente;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtRuaAtendente;
    private javax.swing.JTextField txtSalarioAtendente;
    private javax.swing.JTextField txtTelefoneAtendente;
    // End of variables declaration//GEN-END:variables
}
