/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getaxi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ronaldinho Augusto
 */
public class cadastroCorridaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form telaCliente
     */    
    
    private int protocolo;
    
    public cadastroCorridaJFrame() {
        initComponents(); 
        consultarID();
    }

    public void consultarID()
    {
        ResultSet rs;
        
        // TODO add your handling code here:
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");            
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("SELECT protocolo from chamada");
            rs = instrucao.executeQuery();                                                         
            
            while(rs.next())
            {
                protocolo = rs.getInt(1);
            }
            protocolo += 1;
            txtProtocolo.setText(""+protocolo);

        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblNOMEPassageiro = new javax.swing.JLabel();
        lblMOTORISTASDisponiveis = new javax.swing.JLabel();
        lblMotorista = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblProtocolo = new javax.swing.JLabel();
        lblAtendente = new javax.swing.JLabel();
        lblLocalPartida = new javax.swing.JLabel();
        lblLocalChegada = new javax.swing.JLabel();
        txtNOME = new JtextFieldSomenteLetras(45);
        txtMOTORISTA = new JtextFieldSomenteNumeros();
        txtProtocolo = new javax.swing.JTextField();
        txtIDAtendente = new JtextFieldSomenteNumeros();
        txtLocalPartida = new JtextFieldSomenteLetras(50);
        txtLocalChegada = new JtextFieldSomenteLetras(50);
        btnEnviarMotorista = new javax.swing.JButton();
        btnConsultarMotoristas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMotoristasDisp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Motorista");
        setResizable(false);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CADASTRAR CORRIDA");

        lblNOMEPassageiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNOMEPassageiro.setText("NOME PASSAGEIRO:");

        lblMOTORISTASDisponiveis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMOTORISTASDisponiveis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMOTORISTASDisponiveis.setText("MOTORISTAS DISPONÍVEIS");

        lblMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMotorista.setText("ID MOTORISTA:");

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/iconLocal.png"))); // NOI18N

        lblProtocolo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProtocolo.setText("PROTOCOLO:");

        lblAtendente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAtendente.setText("ID ATENDENTE:");

        lblLocalPartida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocalPartida.setText("LOCAL PARTIDA:");

        lblLocalChegada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocalChegada.setText("LOCAL CHEGADA:");

        txtNOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMEActionPerformed(evt);
            }
        });

        txtMOTORISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMOTORISTAActionPerformed(evt);
            }
        });

        txtProtocolo.setEditable(false);
        txtProtocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProtocoloActionPerformed(evt);
            }
        });

        btnEnviarMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEnviarMotorista.setText("ENVIAR MOTORISTA");
        btnEnviarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMotoristaActionPerformed(evt);
            }
        });

        btnConsultarMotoristas.setText("CONSULTAR MOTORISTAS");
        btnConsultarMotoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMotoristasActionPerformed(evt);
            }
        });

        tblMotoristasDisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idMotorista", "nome", "telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMotoristasDisp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMotoristasDisp);
        if (tblMotoristasDisp.getColumnModel().getColumnCount() > 0) {
            tblMotoristasDisp.getColumnModel().getColumn(0).setResizable(false);
            tblMotoristasDisp.getColumnModel().getColumn(1).setResizable(false);
            tblMotoristasDisp.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIcon)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblProtocolo)
                            .addGap(70, 70, 70)
                            .addComponent(txtProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblAtendente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtIDAtendente))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblMOTORISTASDisponiveis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarMotoristas))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLocalChegada)
                                        .addComponent(lblLocalPartida))
                                    .addGap(38, 38, 38))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblNOMEPassageiro)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNOME)
                                .addComponent(txtLocalPartida)
                                .addComponent(txtLocalChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMOTORISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnEnviarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProtocolo)
                    .addComponent(lblAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIDAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNOMEPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMOTORISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLocalPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocalPartida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLocalChegada)
                    .addComponent(txtLocalChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMOTORISTASDisponiveis))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMotoristaActionPerformed
        // TODO add your handling code here:
        try
        {
            boolean isOk = false;
            
            if(txtNOME.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Favor digitar um nome valido (ate 50 caracteres, sem numeros)");
                isOk = false;                
            }
            if(txtIDAtendente.getText().isEmpty() || txtLocalChegada.getText().isEmpty() || txtLocalPartida.getText().isEmpty() || txtMOTORISTA.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Favor revisar os campos: IDAtendente / Nome Passageiro / IDMotorista / Local Partida / Local Chegada");
                isOk = false;
            }
            
            else
            {
                isOk = true;
            }                         

            if(isOk)
            {
                        
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");            
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("INSERT INTO chamada VALUES(?,?,?,?)");
            instrucao.setInt(1, protocolo);             
            instrucao.setString(2,txtNOME.getText().toUpperCase());
            instrucao.setString(3, txtLocalPartida.getText().toUpperCase());
            instrucao.setString(4, txtLocalChegada.getText().toUpperCase());
            
            PreparedStatement instrucao2 = conexao.prepareStatement("INSERT INTO registro_chamada VALUES(?,?,?)");
            instrucao2.setInt(1, protocolo);             
            instrucao2.setInt(2,Integer.parseInt(txtIDAtendente.getText()));
            instrucao2.setInt(3,Integer.parseInt(txtMOTORISTA.getText()));
            
            //executando a SQL parametrizada
            instrucao.executeUpdate();
            instrucao2.executeUpdate();            
            JOptionPane.showMessageDialog(null,"CORRIDA CADASTRADA! MOTORISTA A CAMINHO.");
            protocolo++;
            
            txtProtocolo.setText(""+protocolo);
            txtIDAtendente.setText("");
            txtLocalChegada.setText("");
            txtLocalPartida.setText("");
            txtMOTORISTA.setText("");
            txtNOME.setText("");
            
            }
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }
    }//GEN-LAST:event_btnEnviarMotoristaActionPerformed

    private void txtNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMEActionPerformed

    private void btnConsultarMotoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMotoristasActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");            
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("SELECT idMotorista,nome,telefone FROM motorista");                        
            rs = instrucao.executeQuery();
            tblMotoristasDisp.setModel(DbUtils.resultSetToTableModel(rs));                        
            
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }    

        
    }//GEN-LAST:event_btnConsultarMotoristasActionPerformed

    private void txtProtocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProtocoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProtocoloActionPerformed

    private void txtMOTORISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMOTORISTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMOTORISTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new cadastroCorridaJFrame().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarMotoristas;
    private javax.swing.JButton btnEnviarMotorista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtendente;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLocalChegada;
    private javax.swing.JLabel lblLocalPartida;
    private javax.swing.JLabel lblMOTORISTASDisponiveis;
    private javax.swing.JLabel lblMotorista;
    private javax.swing.JLabel lblNOMEPassageiro;
    private javax.swing.JLabel lblProtocolo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMotoristasDisp;
    private javax.swing.JTextField txtIDAtendente;
    private javax.swing.JTextField txtLocalChegada;
    private javax.swing.JTextField txtLocalPartida;
    private javax.swing.JTextField txtMOTORISTA;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtProtocolo;
    // End of variables declaration//GEN-END:variables
}
