/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getaxi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ronaldinho Augusto
 */
public class consultarCorridaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form telaCliente
     */
    public consultarCorridaJFrame() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMOTORISTASDisponiveis = new javax.swing.JLabel();
        btnConsultarMotoristas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCorridasAlocadas = new javax.swing.JTable();
        lblCancelarCorrida = new javax.swing.JLabel();
        txtPlacaCancelada = new javax.swing.JTextField();
        btnCancelarCorrida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Motorista");
        setResizable(false);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CONSULTAR CORRIDA");

        lblMOTORISTASDisponiveis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMOTORISTASDisponiveis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMOTORISTASDisponiveis.setText("CORRIDAS ALOCADAS");

        btnConsultarMotoristas.setText("CONSULTAR CORRIDAS ALOCADAS");
        btnConsultarMotoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMotoristasActionPerformed(evt);
            }
        });

        tblCorridasAlocadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nomepassageiro", "cpfpassageiro", "motorista", "placa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCorridasAlocadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCorridasAlocadas);

        lblCancelarCorrida.setText("CANCELAR POR PLACA:");

        btnCancelarCorrida.setText("CANCELAR CORRIDA");
        btnCancelarCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCorridaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCancelarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlacaCancelada, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMOTORISTASDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarMotoristas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMOTORISTASDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCancelarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlacaCancelada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCorrida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarMotoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMotoristasActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");
            JOptionPane.showMessageDialog(null,"CONSULTA REALIZADA!");
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("SELECT * FROM corridas");                        
            rs = instrucao.executeQuery();
            tblCorridasAlocadas.setModel(DbUtils.resultSetToTableModel(rs));                        
            
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }    

        
    }//GEN-LAST:event_btnConsultarMotoristasActionPerformed

    private void btnCancelarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCorridaActionPerformed
        // TODO add your handling code here:
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");
            JOptionPane.showMessageDialog(null,"CONEXAO REALIZADA!");
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("DELETE FROM corridas WHERE placa = ?");            
            instrucao.setString(1,txtPlacaCancelada.getText());                                
            //executando a SQL parametrizada
            instrucao.executeUpdate();
            JOptionPane.showMessageDialog(null,"CORRIDA CANCELADA!");
            
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }
    }//GEN-LAST:event_btnCancelarCorridaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new consultarCorridaJFrame().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCorrida;
    private javax.swing.JButton btnConsultarMotoristas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancelarCorrida;
    private javax.swing.JLabel lblMOTORISTASDisponiveis;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCorridasAlocadas;
    private javax.swing.JTextField txtPlacaCancelada;
    // End of variables declaration//GEN-END:variables
}
