/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getaxi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ronaldinho Augusto
 */
public class consultarCorridaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form telaCliente
     */
    public consultarCorridaJFrame() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMOTORISTASDisponiveis = new javax.swing.JLabel();
        lblPesquisarProtocolo = new javax.swing.JLabel();
        lblIconLocal = new javax.swing.JLabel();
        txtPesquisarProtocolo = new javax.swing.JTextField();
        btnConsultarCorridas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCorridasAlocadas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultaProtocolo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Motorista");
        setResizable(false);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CONSULTAR CORRIDA");

        lblMOTORISTASDisponiveis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMOTORISTASDisponiveis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMOTORISTASDisponiveis.setText("CORRIDAS ALOCADAS");

        lblPesquisarProtocolo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPesquisarProtocolo.setText("PESQUISAR PASSAGEIRO:");

        lblIconLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/iconLocal.png"))); // NOI18N

        txtPesquisarProtocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarProtocoloActionPerformed(evt);
            }
        });
        txtPesquisarProtocolo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarProtocoloKeyReleased(evt);
            }
        });

        btnConsultarCorridas.setText("CONSULTAR CORRIDAS ALOCADAS");
        btnConsultarCorridas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCorridasActionPerformed(evt);
            }
        });

        tblCorridasAlocadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "protocolo", "idatendente", "idmotorista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCorridasAlocadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCorridasAlocadas);
        if (tblCorridasAlocadas.getColumnModel().getColumnCount() > 0) {
            tblCorridasAlocadas.getColumnModel().getColumn(0).setResizable(false);
            tblCorridasAlocadas.getColumnModel().getColumn(1).setResizable(false);
            tblCorridasAlocadas.getColumnModel().getColumn(2).setResizable(false);
        }

        tblConsultaProtocolo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "protocolo", "nomepassageiro", "idmotorista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsultaProtocolo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblConsultaProtocolo);
        if (tblConsultaProtocolo.getColumnModel().getColumnCount() > 0) {
            tblConsultaProtocolo.getColumnModel().getColumn(0).setResizable(false);
            tblConsultaProtocolo.getColumnModel().getColumn(1).setResizable(false);
            tblConsultaProtocolo.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/iconSearch.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblMOTORISTASDisponiveis)
                        .addGap(257, 257, 257)
                        .addComponent(btnConsultarCorridas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPesquisarProtocolo)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisarProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblIconLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarCorridas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMOTORISTASDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCorridasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCorridasActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");            
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao = conexao.prepareStatement("SELECT * FROM registro_chamada");                        
            rs = instrucao.executeQuery();
            tblCorridasAlocadas.setModel(DbUtils.resultSetToTableModel(rs));                        
            
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }    

        
    }//GEN-LAST:event_btnConsultarCorridasActionPerformed

    public void pesquisarProtocolo()
    {
        ResultSet rs;        
        
        try
        {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexao com o SGDB PostgreSQL
            Connection conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "senha123");            
            //construcao da classe PreparedStatement para passagem de parametros
            PreparedStatement instrucao2 = conexao.prepareStatement("SELECT protocolo,passageiro FROM chamada WHERE passageiro like ?");                        
            instrucao2.setString(1, (txtPesquisarProtocolo.getText()+"%"));
            rs = instrucao2.executeQuery();
            tblConsultaProtocolo.setModel(DbUtils.resultSetToTableModel(rs));                        
            
        }catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: "+ e.getMessage());
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+ e.getMessage());
        }
        
    }
    
    private void txtPesquisarProtocoloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarProtocoloKeyReleased
        // TODO add your handling code here:
        pesquisarProtocolo();
    }//GEN-LAST:event_txtPesquisarProtocoloKeyReleased

    private void txtPesquisarProtocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarProtocoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarProtocoloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultarCorridaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new consultarCorridaJFrame().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCorridas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIconLocal;
    private javax.swing.JLabel lblMOTORISTASDisponiveis;
    private javax.swing.JLabel lblPesquisarProtocolo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblConsultaProtocolo;
    private javax.swing.JTable tblCorridasAlocadas;
    private javax.swing.JTextField txtPesquisarProtocolo;
    // End of variables declaration//GEN-END:variables
}
